// app/layout.js
import "./globals.css";

export const metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
  icons: {
    icon: "/public/next.svg", 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
        <main>{children}</main>
      </body>
    </html>
  );
}
